version: "3.8"
services:

  # Business Layer
  login_business:
    build: ./business_logic_layer
    restart: always
    environment:
      - AUTH_ADAPTER_PORT
      - LOGIN_BUSINESS_PORT
    ports:
      - ${LOGIN_BUSINESS_PORT}:${LOGIN_BUSINESS_PORT}
    expose:
      - ${LOGIN_BUSINESS_PORT}
    depends_on:
      - auth_db_adapter

  # Adapter Layer
  auth_db_adapter:
    build: ./adapter_layer/auth_db_interface
    restart: always
    environment:
      - AUTH_ADAPTER_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - ${AUTH_ADAPTER_PORT}:${AUTH_ADAPTER_PORT}
    expose:
      - ${AUTH_ADAPTER_PORT}
    depends_on: 
      - database
  
  database:
    image: mysql:8.3
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    expose:
      - ${AUTH_DB_PORT}