version: "3.8"
services:

  # Process Layer
  authentication:
    build: ./process_centric_layer/authentication
    restart: always
    environment:
      - AUTHENTICATION_PROCESS_PORT
      - LOGIN_BUSINESS_PORT
      - REGISTRATION_BUSINESS_PORT
    ports:
      - ${AUTHENTICATION_PROCESS_PORT}:${AUTHENTICATION_PROCESS_PORT}
    expose:
      - ${AUTHENTICATION_PROCESS_PORT}
    depends_on:
      - login_business
      - registration_business
  overview:
    build: ./process_centric_layer/full_film_overview
    restart: always
    environment:
      - FULL_OVERVIEW_PORT
      - FULL_DETAIL_PORT
      - FULL_REVIEW_PORT
    ports:
      - ${FULL_OVERVIEW_PORT}:${FULL_OVERVIEW_PORT}
    expose:
      - ${FULL_OVERVIEW_PORT}
  # Business Layer
  login_business:
    build: ./business_logic_layer/login
    restart: always
    environment:
      - AUTH_ADAPTER_PORT
      - LOGIN_BUSINESS_PORT
      - JWT_SECRET
    ports:
      - ${LOGIN_BUSINESS_PORT}:${LOGIN_BUSINESS_PORT}
    expose:
      - ${LOGIN_BUSINESS_PORT}
    depends_on:
      - auth_db_adapter
  full_detail_business:
    build: ./business_logic_layer/details
    restart: always
    environment:
      - FULL_DETAIL_PORT
      - IMDB_DETAIL_PORT
      - TMDB_DETAIL_PORT
    ports:
      - ${FULL_DETAIL_PORT}:${FULL_DETAIL_PORT}
    expose:
      - ${FULL_DETAIL_PORT}
  full_review_business:
    build: ./business_logic_layer/reviews
    restart: always
    environment:
      - FULL_REVIEW_PORT
      - IMDB_REVIEW_PORT
      - TMDB_REVIEW_PORT
    ports:
      - ${FULL_REVIEW_PORT}:${FULL_REVIEW_PORT}
    expose:
      - ${FULL_REVIEW_PORT}

  registration_business:
    build: ./business_logic_layer/registration
    restart: always
    environment:
      - AUTH_ADAPTER_PORT
      - REGISTRATION_BUSINESS_PORT
    ports:
      - ${REGISTRATION_BUSINESS_PORT}:${REGISTRATION_BUSINESS_PORT}
    expose:
      - ${REGISTRATION_BUSINESS_PORT}
    depends_on:
      - auth_db_adapter

  streaming_avaibility_business:
   build: ./business_logic_layer/streaming_availability
   restart: always
   environment:
     - STREAMING_AVAILABILITY_PORT
     - TMDB_DETAIL_PORT
     - AVAILABILITY_STREAMING_BUSINESS_PORT
   ports:
     - ${AVAILABILITY_STREAMING_BUSINESS_PORT}:${AVAILABILITY_STREAMING_BUSINESS_PORT}
   expose:
     - ${AVAILABILITY_STREAMING_BUSINESS_PORT}
   depends_on:
     - tmdb_detail_adapter
  # Adapter Layer
  auth_db_adapter:
    build: ./adapter_layer/auth_db_interface
    restart: always
    environment:
      - AUTH_ADAPTER_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - ${AUTH_ADAPTER_PORT}:${AUTH_ADAPTER_PORT}
    expose:
      - ${AUTH_ADAPTER_PORT}
    depends_on: 
      - database
  

  imdb_detail_adapter:
    build: ./adapter_layer/imdb_detail_api
    restart: always
    environment:
      - IMDB_DETAIL_PORT
      - X_RAPIDAPI_KEY
    ports:
      - ${IMDB_DETAIL_PORT}:${IMDB_DETAIL_PORT}
    expose:
      - ${IMDB_DETAIL_PORT}

  tmdb_detail_adapter:
    build: ./adapter_layer/tmdb_detail_api
    restart: always
    environment:
      - TMDB_DETAIL_PORT
      - TMDB_AUTHORIZATION
    ports:
      - ${TMDB_DETAIL_PORT}:${TMDB_DETAIL_PORT}
    expose:
      - ${TMDB_DETAIL_PORT}
  imdb_review_adapter:
    build: ./adapter_layer/imdb_review_api
    restart: always
    environment:
      - IMDB_REVIEW_PORT
      - X_RAPIDAPI_KEY
    ports:
      - ${IMDB_REVIEW_PORT}:${IMDB_REVIEW_PORT}
    expose:
      - ${IMDB_REVIEW_PORT}

  tmdb_review_adapter:
    build: ./adapter_layer/tmdb_review_api
    restart: always
    environment:
      - TMDB_REVIEW_PORT
      - TMDB_AUTHORIZATION
    ports:
      - ${TMDB_REVIEW_PORT}:${TMDB_REVIEW_PORT}
    expose:
      - ${TMDB_REVIEW_PORT}
  
  streaming_availability_adapter:
    build: ./adapter_layer/streaming_availability_api
    restart: always
    environment:
      - STREAMING_AVAILABILITY_PORT
      - X_RAPIDAPI_KEY
    ports:
      - ${STREAMING_AVAILABILITY_PORT}:${STREAMING_AVAILABILITY_PORT}
    expose:
      - ${STREAMING_AVAILABILITY_PORT}

  database:
    image: mysql:8.3
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    expose:
      - ${AUTH_DB_PORT}
    volumes:
      - user-db:/var/lib/mysql
      
volumes:
  user-db: